// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzvv5kTR-FJTQwPqfDZaIOk6SN8JVUeaA',
    appId: '1:1035202572787:web:6d5a2b4d7394d18f5aa286',
    messagingSenderId: '1035202572787',
    projectId: 'capstone-ti-1',
    authDomain: 'capstone-ti-1.firebaseapp.com',
    storageBucket: 'capstone-ti-1.firebasestorage.app',
    measurementId: 'G-3TJBV8ZVTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJVujm_Tg3usdUzzt-8e4cRuJV8OZiXg',
    appId: '1:1035202572787:android:43849d25e8bfc6445aa286',
    messagingSenderId: '1035202572787',
    projectId: 'capstone-ti-1',
    storageBucket: 'capstone-ti-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kzgz_PqTmRTch1OdOD_8iK7I13C0VAA',
    appId: '1:1035202572787:ios:23c2c87cc6734f385aa286',
    messagingSenderId: '1035202572787',
    projectId: 'capstone-ti-1',
    storageBucket: 'capstone-ti-1.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0kzgz_PqTmRTch1OdOD_8iK7I13C0VAA',
    appId: '1:1035202572787:ios:23c2c87cc6734f385aa286',
    messagingSenderId: '1035202572787',
    projectId: 'capstone-ti-1',
    storageBucket: 'capstone-ti-1.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzvv5kTR-FJTQwPqfDZaIOk6SN8JVUeaA',
    appId: '1:1035202572787:web:787a948900f230885aa286',
    messagingSenderId: '1035202572787',
    projectId: 'capstone-ti-1',
    authDomain: 'capstone-ti-1.firebaseapp.com',
    storageBucket: 'capstone-ti-1.firebasestorage.app',
    measurementId: 'G-VJE8ETF3TK',
  );
}
